#!/bin/bash
[ "$1" = -x ] && shift && set -x

generate_ipout_global()
   {
      [ -f /etc/rose/ipout/.global ] && return 0
      #### allow name resolution (read from resolv.conf)
      while read key value x
         do
            [ "$key" = nameserver ] || continue
            printf "proto=%s rule=%-30s desc=%s\n" tcp "$value|53" "name resolution"
            printf "proto=%s rule=%-30s desc=%s\n" udp "$value|53" "name resolution"
         done \
      <  /etc/resolv.conf \
      >  /etc/rose/ipout/.global
      exit $?
   }

generate_ipout_apt()
   {
      #### allow package updates (install software if needed)
      cat /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null \
      |  sed '/#/d; /^$/d; s/[:/]/ /g; s/  */ /g' \
      |  cut -d \  -f 1-3 \
      |  sort -u \
      |  while read type proto hostname
            do
               case "$proto"
                  in
                     http) port=80;;
                     https) port=443;;
                     *) continue;;
                  esac
               printf "proto=tcp rule=%-30s desc=%s\n" "$hostname|$port" "get new packages"
            done \
      > /etc/rose/ipout/_apt
      exit $?
   }

case "$1"
   in
      global) generate_ipout_global;;
      apt)    generate_ipout_apt;;
      *)      echo "this option is not supported" >&2
              echo "usage: $0 [-x] {global|apt}" >&2
              exit 2;;
   esac
exit 0
