#!/bin/bash
##### global variable:
##### LoginSleep        time to sleep, executing this scipt...
#####                   default=3600
[ -f /etc/default/LoginSleep ] && source /etc/default/LoginSleep

printf "\r\n--------------------------------------------------\r\n"
printf     "     connection successful -- ready to tunnel"
printf "\r\n--------------------------------------------------\r\n"

file="/etc/rose/ipout/.current/$USER"
if [ "$2" = rules ] && [ -f "$file" ]
   then
      echo
      cat "$file"
      echo
   fi

sleep "${LoginSleep:-3600}"
exit $?
